# Gems host
source 'http://rubygems.org'

gem 'rails', '~> 3.0.5' # At least 3.0.5 but below 3.1
gem 'mysql2'            # Database engine
gem 'hirb'              # Better console formatting. Needs .hirbrc

gem 'capistrano'        # Deployment manager

gem 'haml', '~> 3.0'    # Haml (html/erb replacement) and Sass (css replacement)
gem 'haml-rails'        # Haml generators for Rails 3

# HTML/CSS framework and boilerplate
gem 'compass', '>= 0.10.6'
gem 'html5-boilerplate'
# gem 'compass-960-plugin'

gem 'friendly_id', '~> 3.2'         # Human readable URLs
gem 'validates_existence', '~> 0.5' # Validation of associations

# Optional gems below:

# gem 'devise', '~> 1.1'        # User authentication (accounts)
# gem 'hpricot'                 # For Devise view generation
# gem 'ruby_parser'             # For Devise view generation
# gem 'cancan', '~> 1.5.1'      # User authorization (permissions)

# gem 'kramdown', '~> 0.13'     # To convert Markdown to HTML
# gem 'will_paginate', '~> 3.0.pre2'  # Pagination of long lists
# gem 'paperclip', '~> 2.3.8'   # File upload management

# gem 'vestal_versions'         # To track changes to pages and other objects
# gem 'paper_trail'             # To track changes to pages and other objects

group :development, :test do
  gem 'factory_girl_rails', '~> 1.0'
  gem 'factory_girl_generator'
  gem 'rspec-rails', '~> 2.5'
  gem 'rcov'
  gem 'forgery'                     # Easy generation of fake data
end
